import type { Metadata } from "next";
import { Poppins, Montserrat, DM_Sans } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const mont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mont",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const dm = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Corpreal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // useMontserrat = false,
// useDm = true,
Readonly<{
  children: React.ReactNode;
  // useMontserrat?: boolean;
  // useDm?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} ${mont.variable} ${dm.variable}`}>
        {children}
      </body>
    </html>
  );
}
