import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const mont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mont",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Corpreal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  useMontserrat = false,
}: Readonly<{
  children: React.ReactNode;
  useMontserrat?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={useMontserrat ? mont.className : poppins.className}>
        {children}
      </body>
    </html>
  );
}
